title: Mt's Academic Homepage
page-top-title: Mt
top-section-bg-text: Research · Innovation · Excellence
home-subtitle: 中南大学研究生&ensp;|&ensp;控制科学与工程
copyright-text: '&copy; Mt 2024-2025. All Rights Reserved.'
